import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss"
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import HomeCart from "@/components/homeCart/HomeCart";
import ProjectsCart from "@/components/projectsCart/ProjectsCart";
import ContactCart from "@/components/contactCart/ContactCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className="container">
        <Navbar />
        <HomeCart />
        <ProjectsCart />
        <ContactCart />
        <Footer />
        </div>
      </body>
    </html>
  );
}
